Repository openshift-assisted/assisted-service-mcp, pull requests merged in 2025-08, with the labels that each got.

#52 MGMT-21236: Allow setting cpu arch when creating a cluster
  server.py
  tests/test_server.py
Labels: size/M, lgtm, jira/valid-reference, approved

#59 MGMT-21086: Set TRANSPORT in template to streamable-http
  template.yaml
Labels: lgtm, jira/valid-reference, approved, size/XS

#62 MGMT-21356: Add operator names to tool description
  server.py
Labels: lgtm, jira/valid-reference, approved, size/XS

#63 add ServiceAccount to openshift template
  template.yaml
Labels: lgtm, approved, size/XS

#65 adding the deployment script to the corresponding repository
  Makefile
  scripts/deploy_from_template.sh
Labels: size/M, lgtm, approved

#66 MGMT-21476: Increase resources
  template.yaml
Labels: lgtm, jira/valid-reference, approved, size/XS

#67 MGMT-21387: Add metrics for just the assisted service API calls
  metrics/__init__.py
  metrics/metrics.py
  server.py
  service_client/__init__.py
  service_client/assisted_service_api.py
Labels: size/M, lgtm, jira/valid-reference, approved

#74 MGMT-21600: Remove cluster name validation from the mcp server
  server.py
Labels: jira/valid-reference, approved, size/XS
