Repository openshift-assisted/assisted-service-mcp, pull requests merged in 2025-09, with the labels that each got.

#78 Add myself (Ben) to OWNERS
  OWNERS
Labels: lgtm, approved, size/XS, ok-to-test

#83 adding the tag latest to the konflux builds, so getting the latest image would be easier
  .tekton/assisted-service-mcp-saas-main-push.yaml
  scripts/deploy_from_template.sh
Labels: size/M, lgtm, approved

#84 change the assisted-service connection from production to staging
  scripts/deploy_from_template.sh
Labels: lgtm, approved, size/XS

#89 changeing the pull secret for the mcp server so the evaluation tests could succeed
  scripts/deploy_from_template.sh
Labels: lgtm, size/XS

#88 MGMT-21692 Update set_host_role to use cluster_id instead of infraenv_id
  server.py
  tests/test_server.py
Labels: size/M, lgtm, approved

#102 Clarify semantics of alter_static_network_config_nmstate_for_host
  server.py
Labels: lgtm, approved, size/XS

#105 Add metric param for static route templating
  static_net/template.py
  tests/test_static_net.py
Labels: lgtm, approved, size/S
