Repository openshift-assisted/assisted-service-mcp, pull requests merged in 2025-07, with the labels that each got.

#7 adding a tag to denote cluster was created via mcp
  server.py
Labels: size/XS

#8 fix git repo url
  README.md
Labels: size/XS

#19 MGMT-21040: Hide the infraenv concept better
  README.md
  server.py
  service_client/assisted_service_api.py
  tests/test_assisted_service_api.py
  tests/test_server.py
Labels: size/L, jira/valid-reference

#23 updating image location
  template.yaml
Labels: size/XS

#24 Add log level env
  template.yaml
Labels: lgtm, size/XS

#22 MGMT-21039: Add a tool for getting URLs for cluster credentials
  server.py
  service_client/assisted_service_api.py
  tests/test_assisted_service_api.py
  tests/test_server.py
Labels: size/L, jira/valid-reference

#31 Refresh the ISO URL when returning it
  server.py
  service_client/assisted_service_api.py
  tests/test_assisted_service_api.py
  tests/test_server.py
Labels: size/L, lgtm

#32 Lazy load pull secret
  service_client/assisted_service_api.py
  tests/test_assisted_service_api.py
Labels: size/M

#35 Implement Prometheus metrics endpoint
  README.md
  pyproject.toml
  server.py
  service_client/__init__.py
  service_client/metrics.py
Labels: size/L, ok-to-test

#36 add name to Service in OpenShift template
  template.yaml
Labels: size/XS

#41 adding OWNERS
  OWNERS
Labels: size/S

#38 MGMT-21086: support different protocols
  pyproject.toml
  server.py
  template.yaml
  tests/test_server.py
  uv.lock
Labels: lgtm, jira/valid-reference, approved, size/XL

#43 Revert "MGMT-21086: support different protocols"
  pyproject.toml
  server.py
  template.yaml
  tests/test_server.py
  uv.lock
Labels: lgtm, jira/valid-reference, approved, size/XL

#44 MGMT-21113: Return less on error
  service_client/assisted_service_api.py
  service_client/exceptions.py
  tests/test_assisted_service_api.py
Labels: lgtm, jira/valid-reference, approved, size/XL

#47 MGMT-21215: Allow setting or updating cluster ssh public key
  README.md
  doc/example_prompts.md
  server.py
  service_client/assisted_service_api.py
  tests/test_assisted_service_api.py
  tests/test_server.py
Labels: size/L, lgtm, jira/valid-reference, approved

#48 MGMT-21296: Add validation info for cluster name in cluster create tool description
  server.py
Labels: lgtm, jira/valid-reference, approved, size/XS
